name: build

on: [push, pull_request]

jobs:
  macos:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: install dependencies
        run: HOMEBREW_OPTFLAGS="-march=core2" HOMEBREW_OPTIMIZATION_LEVEL="O0" HOMEBREW_NO_AUTO_UPDATE=1 brew install qt@5 libsodium libzip qrencode unbound cmake boost hidapi openssl expat libunwind-headers protobuf pkgconfig zbar
      - name: build
        run: CMAKE_PREFIX_PATH=/usr/local/opt/qt@5/ make mac-release -j3
      - name: create .tar
        run: tar -cf feather.tar feather.app
        working-directory: build/bin
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: build/bin/feather.tar
