name: build

on: [push, pull_request]

jobs:
  macos:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install qt@5 libsodium libzip qrencode unbound cmake hidapi openssl expat libunwind-headers protobuf pkgconfig zbar
      - name: install boost 1.75.0
        run: HOMEBREW_OPTFLAGS="-march=core2" HOMEBREW_OPTIMIZATION_LEVEL="O0" HOMEBREW_NO_AUTO_UPDATE=1 brew install ./boost.rb
      - name: install polyseed
        run: git clone https://github.com/tevador/polyseed.git && cd polyseed && git reset --hard e38516561c647522e2e2608f13eabdeab61d9a5d && cmake . && make && make install
      - name: build
        run: CMAKE_PREFIX_PATH='/usr/local/opt/qt@5/' CMAKE_INCLUDE_PATH=/usr/local/opt/boost@1.76/include LDFLAGS="-L/usr/local/opt/boost@1.76/lib" make mac-release -j3
      - name: create .tar
        run: tar -cf feather.tar feather.app
        working-directory: build/bin
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: build/bin/feather.tar
